// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/hosts/hosts.proto

package top_goox_srv_hosts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Hosts service

type HostsService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Hosts_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Hosts_PingPongService, error)
}

type hostsService struct {
	c    client.Client
	name string
}

func NewHostsService(name string, c client.Client) HostsService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "top.goox.srv.hosts"
	}
	return &hostsService{
		c:    c,
		name: name,
	}
}

func (c *hostsService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Hosts.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Hosts_StreamService, error) {
	req := c.c.NewRequest(c.name, "Hosts.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &hostsServiceStream{stream}, nil
}

type Hosts_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type hostsServiceStream struct {
	stream client.Stream
}

func (x *hostsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *hostsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hostsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hostsServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hostsService) PingPong(ctx context.Context, opts ...client.CallOption) (Hosts_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Hosts.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &hostsServicePingPong{stream}, nil
}

type Hosts_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type hostsServicePingPong struct {
	stream client.Stream
}

func (x *hostsServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *hostsServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hostsServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hostsServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *hostsServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Hosts service

type HostsHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Hosts_StreamStream) error
	PingPong(context.Context, Hosts_PingPongStream) error
}

func RegisterHostsHandler(s server.Server, hdlr HostsHandler, opts ...server.HandlerOption) error {
	type hosts interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Hosts struct {
		hosts
	}
	h := &hostsHandler{hdlr}
	return s.Handle(s.NewHandler(&Hosts{h}, opts...))
}

type hostsHandler struct {
	HostsHandler
}

func (h *hostsHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.HostsHandler.Call(ctx, in, out)
}

func (h *hostsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.HostsHandler.Stream(ctx, m, &hostsStreamStream{stream})
}

type Hosts_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type hostsStreamStream struct {
	stream server.Stream
}

func (x *hostsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *hostsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hostsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hostsStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *hostsHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.HostsHandler.PingPong(ctx, &hostsPingPongStream{stream})
}

type Hosts_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type hostsPingPongStream struct {
	stream server.Stream
}

func (x *hostsPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *hostsPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hostsPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hostsPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *hostsPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
